workflows:
  react-native-android:
    name: React Native Android Build
    max_build_duration: 60
    environment:
      node: 18
      java: 17
      android: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build Android debug APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk
